"""The cannet wire encoding, in Python.

Everything both ends of the wire have to agree on lives here, so there
is exactly one encoding of it in this repository and nothing that can
drift: the checked-in gRPC gencode (:mod:`cannet_python_wire._proto`,
regenerated by ``scripts/regen_proto.sh``), the
:class:`~cannet_python_wire.frame.Frame` dataclass either side passes
around, and the mappers that take it to the generated proto type
(:mod:`cannet_python_wire.proto`) and to a python-can ``Message``
(:mod:`cannet_python_wire.python_can`).

Nothing here talks to hardware, opens a socket, or serves an RPC. The
sidecar that exposes local adapters and the python-can client that
opens a bus on a server are both consumers of this package.
"""

from __future__ import annotations

from .frame import Frame, FrameKind
from .proto import frame_to_proto, proto_to_frame
from .python_can import frame_to_message, message_to_frame

__version__ = "0.1.0"

__all__ = [
    "Frame",
    "FrameKind",
    "__version__",
    "frame_to_message",
    "frame_to_proto",
    "message_to_frame",
    "proto_to_frame",
]
