use vergen::EmitBuilder;

fn main() {
    // Emit `VERGEN_GIT_DESCRIBE` (`git describe --tags --dirty`) so the
    // running app can report the exact tag/commit it was built from.
    // Best-effort: a build outside a git checkout (e.g. from a source
    // tarball) simply doesn't set the var, and the app falls back to the
    // Cargo crate version — see `build_version` in `lib.rs`.
    let _ = EmitBuilder::builder().git_describe(true, true, None).emit();
    // A dev build must compile before the sidecar has ever been frozen:
    // `tauri.conf.json` declares `sidecar-dist/cannet-python-can` and
    // `licenses.json` as resources, and tauri-build fails on a missing
    // resource path. Create the (gitignored) placeholders so a fresh
    // checkout can `cargo build`/`test`/`clippy` and `tauri dev` — at
    // runtime dev builds prefer the sidecar source tree anyway (see
    // `sidecar::plan_launch`), and the license manifest resolves to an
    // empty attribution surface (see `licenses::third_party_licenses`).
    // Release builds keep the hard failure: bundling an empty sidecar dir
    // or an empty manifest would ship an incomplete installer. The real
    // manifest is generated by `scripts/build-sidecar.py` before a release
    // bundle, so it overwrites this placeholder when present.
    if std::env::var("PROFILE").as_deref() == Ok("debug") {
        let _ = std::fs::create_dir_all("sidecar-dist/cannet-python-can");
        if !std::path::Path::new("licenses.json").exists() {
            let _ = std::fs::write("licenses.json", "{\"components\":[]}\n");
        }
    }
    tauri_build::build();
}
