# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cannet_info_pb2 as cannet__info__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cannet_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CannetInfoStub(object):
    """What a cannet server is, asked before anything else is asked of it.

    This package is deliberately **unversioned and frozen**. It is the one
    thing every cannet server answers whatever protocol majors it serves,
    so a client whose major the server no longer serves still gets a
    sentence it can show a user instead of an opaque `UNIMPLEMENTED` on
    the first real call. Nothing here may ever change incompatibly —
    additions only. The rule the answer is read against is in
    `cannet.proto`'s header; the decision is ADR 0059.

    Unauthenticated by design. ADR 0041's bearer token gates every other
    RPC, and a protocol mismatch has to be reportable before a credential
    is asked for — a client that cannot speak to this server at all
    should not first be told its token is wrong. Nothing here is a
    disclosure: the mDNS advertisement (ADR 0040) already puts the
    instance name, the build version, and now the package list on the
    local network.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerInfo = channel.unary_unary(
                '/cannet.CannetInfo/ServerInfo',
                request_serializer=cannet__info__pb2.ServerInfoRequest.SerializeToString,
                response_deserializer=cannet__info__pb2.ServerInfoResponse.FromString,
                _registered_method=True)


class CannetInfoServicer(object):
    """What a cannet server is, asked before anything else is asked of it.

    This package is deliberately **unversioned and frozen**. It is the one
    thing every cannet server answers whatever protocol majors it serves,
    so a client whose major the server no longer serves still gets a
    sentence it can show a user instead of an opaque `UNIMPLEMENTED` on
    the first real call. Nothing here may ever change incompatibly —
    additions only. The rule the answer is read against is in
    `cannet.proto`'s header; the decision is ADR 0059.

    Unauthenticated by design. ADR 0041's bearer token gates every other
    RPC, and a protocol mismatch has to be reportable before a credential
    is asked for — a client that cannot speak to this server at all
    should not first be told its token is wrong. Nothing here is a
    disclosure: the mDNS advertisement (ADR 0040) already puts the
    instance name, the build version, and now the package list on the
    local network.
    """

    def ServerInfo(self, request, context):
        """Unary. Answers without a token, on every server mode.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CannetInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerInfo,
                    request_deserializer=cannet__info__pb2.ServerInfoRequest.FromString,
                    response_serializer=cannet__info__pb2.ServerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cannet.CannetInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cannet.CannetInfo', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CannetInfo(object):
    """What a cannet server is, asked before anything else is asked of it.

    This package is deliberately **unversioned and frozen**. It is the one
    thing every cannet server answers whatever protocol majors it serves,
    so a client whose major the server no longer serves still gets a
    sentence it can show a user instead of an opaque `UNIMPLEMENTED` on
    the first real call. Nothing here may ever change incompatibly —
    additions only. The rule the answer is read against is in
    `cannet.proto`'s header; the decision is ADR 0059.

    Unauthenticated by design. ADR 0041's bearer token gates every other
    RPC, and a protocol mismatch has to be reportable before a credential
    is asked for — a client that cannot speak to this server at all
    should not first be told its token is wrong. Nothing here is a
    disclosure: the mDNS advertisement (ADR 0040) already puts the
    instance name, the build version, and now the package list on the
    local network.
    """

    @staticmethod
    def ServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cannet.CannetInfo/ServerInfo',
            cannet__info__pb2.ServerInfoRequest.SerializeToString,
            cannet__info__pb2.ServerInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
