# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cannet_pb2 as cannet__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cannet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CannetServerStub(object):
    """CAN frame transport between cannet clients and servers.

    Two RPCs: `ListInterfaces` for on-demand discovery of the interfaces
    a server provides, and `Session` for a single bidirectional Envelope
    stream. Frame movement is symmetric — either side sends frames on a
    subscribed interface using the same wire shape.

    Cyclic / scheduled emission is not modelled at the wire layer.
    Sending on a cadence is a feature of the client transmit UI.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListInterfaces = channel.unary_unary(
                '/cannet.v1.CannetServer/ListInterfaces',
                request_serializer=cannet__pb2.ListInterfacesRequest.SerializeToString,
                response_deserializer=cannet__pb2.InterfaceList.FromString,
                _registered_method=True)
        self.Session = channel.stream_stream(
                '/cannet.v1.CannetServer/Session',
                request_serializer=cannet__pb2.Envelope.SerializeToString,
                response_deserializer=cannet__pb2.Envelope.FromString,
                _registered_method=True)


class CannetServerServicer(object):
    """CAN frame transport between cannet clients and servers.

    Two RPCs: `ListInterfaces` for on-demand discovery of the interfaces
    a server provides, and `Session` for a single bidirectional Envelope
    stream. Frame movement is symmetric — either side sends frames on a
    subscribed interface using the same wire shape.

    Cyclic / scheduled emission is not modelled at the wire layer.
    Sending on a cadence is a feature of the client transmit UI.
    """

    def ListInterfaces(self, request, context):
        """Stateless query: what CAN interfaces does this server expose?
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Session(self, request_iterator, context):
        """A single bidirectional stream of Envelopes for the lifetime of a
        client session. Closing the stream ends the session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CannetServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListInterfaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInterfaces,
                    request_deserializer=cannet__pb2.ListInterfacesRequest.FromString,
                    response_serializer=cannet__pb2.InterfaceList.SerializeToString,
            ),
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=cannet__pb2.Envelope.FromString,
                    response_serializer=cannet__pb2.Envelope.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cannet.v1.CannetServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cannet.v1.CannetServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CannetServer(object):
    """CAN frame transport between cannet clients and servers.

    Two RPCs: `ListInterfaces` for on-demand discovery of the interfaces
    a server provides, and `Session` for a single bidirectional Envelope
    stream. Frame movement is symmetric — either side sends frames on a
    subscribed interface using the same wire shape.

    Cyclic / scheduled emission is not modelled at the wire layer.
    Sending on a cadence is a feature of the client transmit UI.
    """

    @staticmethod
    def ListInterfaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cannet.v1.CannetServer/ListInterfaces',
            cannet__pb2.ListInterfacesRequest.SerializeToString,
            cannet__pb2.InterfaceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cannet.v1.CannetServer/Session',
            cannet__pb2.Envelope.SerializeToString,
            cannet__pb2.Envelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
