// Generate the golden vectors that pin the Rust fzf port
// (`apps/gui/src-tauri/src/fuzzy.rs`) to the TypeScript `fzf` package
// the frontend's filter slot uses (ADR 0044).
//
// The host has to rank the same way the frontend does, so the npm
// package is the oracle: this runs it with exactly the options
// `gridviewFilter.tsx` passes (`casing: "case-insensitive"`, a
// `selector`, everything else default) over a fixture of real names
// pulled from the ev-zonal example databases, and writes the
// score-descending result plus the relative-floor cut.
//
// Run from the repo root:
//
//     node apps/gui/scripts/fzf-golden.mjs
//
// The output is checked in; regenerate it only when the package
// version moves or the fixture changes, and expect the Rust test to be
// the thing that tells you the port drifted.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { Fzf } from "fzf";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
// The package does not export `./package.json`, so read it off disk.
const fzfVersion = JSON.parse(
  readFileSync(join(here, "..", "node_modules", "fzf", "package.json"), "utf8"),
).version;

/// Mirrors `MIN_RELATIVE_SCORE` in `apps/gui/src/gridviewFilter.tsx`.
const MIN_RELATIVE_SCORE = 0.7;

const DBC_FILES = [
  "examples/ev-zonal/dbc/pack.dbc",
  "examples/ev-zonal/dbc/zonal.dbc",
];

/// The names a trace-filter query is matched against, straight out of
/// the DBC text: ECU nodes (`BU_`), message names and their
/// transmitters (`BO_`), signal names (`SG_`) and value-table labels
/// (`VAL_`). Regex rather than a parser because this is a fixture
/// generator, not a consumer of the model.
function namesFromDbc(text) {
  const names = [];
  for (const line of text.split(/\r?\n/)) {
    let m;
    if ((m = /^BU_:\s*(.*)$/.exec(line)) !== null) {
      names.push(...m[1].trim().split(/\s+/).filter(Boolean));
    } else if ((m = /^BO_ (\d+) ([A-Za-z0-9_]+)\s*:\s*\d+\s+([A-Za-z0-9_]+)/.exec(line)) !== null) {
      names.push(m[2], m[3]);
    } else if ((m = /^ SG_ ([A-Za-z0-9_]+)/.exec(line)) !== null) {
      names.push(m[1]);
    } else if ((m = /^VAL_ \d+ ([A-Za-z0-9_]+)\s+(.*);\s*$/.exec(line)) !== null) {
      names.push(m[1]);
      for (const label of m[2].matchAll(/"([^"]*)"/g)) names.push(label[1]);
    }
  }
  return names;
}

const dbcNames = [];
for (const rel of DBC_FILES) {
  dbcNames.push(...namesFromDbc(readFileSync(join(repoRoot, rel), "utf8")));
}

/// Bus names as the ev-zonal project spells them — the one part of the
/// haystack that is user-authored rather than DBC-derived.
const busNames = ["Zonal CAN", "Pack CAN", "Diag CAN"];

/// A handful of entries in the joined shape the host actually builds
/// per `(bus, id, extended)`: bus name, id in both spellings, message
/// name, transmitter, signal names.
const joined = [
  "Zonal CAN s:400 x:00000400 DoorLockStatus BodyGateway LockState CinchState LockEffort",
  "Zonal CAN s:402 x:00000402 WheelSpeedFrontLeft ZoneFrontLeft WheelSpeed WheelDirection WheelPulseCount",
  "Pack CAN s:192 x:000000C0 VcuPackCommand VehicleControlUnit PackEnableRequest PrechargeRequest MaxDischargeCurrentRequest",
  "Pack CAN s:193 x:000000C1 PackStatus BMS PackVoltage PackCurrent PackSoc PackStateOfHealth",
  "Diag CAN s:2015 x:000007DF DiagnosticRequest CentralCompute ServiceId SubFunction DataIdentifier",
];

/// A haystack long enough that `runes * queryRunes` passes the `fzf`
/// slab's 100 KiB ceiling, which is where the package falls back from
/// its v2 matcher to v1. The port has the same cliff, so a vector has
/// to stand on it.
const long = Array.from({ length: 700 }, (_, i) => dbcNames[i % dbcNames.length]).join(" ");

const haystacks = [
  ...new Set([...busNames, ...dbcNames, ...joined]),
];
haystacks.push(long);

const QUERIES = [
  "pack",
  "Pack",
  "PACK",
  "psoc",
  "wheelspd",
  "lock",
  "LockState",
  "zfl",
  "c0",
  "s:192",
  "0000040",
  "pack can",
  "temp",
  "chg",
  "insul",
  "dcdc",
  "state",
  "req",
  "vcu",
  "xyz",
  "thermalcontrol",
];

const fzf = new Fzf(
  haystacks.map((s, i) => ({ i, s })),
  { selector: (e) => e.s, casing: "case-insensitive" },
);

const cases = QUERIES.map((query) => {
  const results = fzf.find(query);
  const ranked = results.map((r) => [r.item.i, r.score]);
  const floor = (results[0]?.score ?? 0) * MIN_RELATIVE_SCORE;
  const kept = [];
  for (const r of results) {
    if (r.score < floor) break;
    kept.push(r.item.i);
  }
  return { query, ranked, kept };
});

const out = {
  note: "Generated by apps/gui/scripts/fzf-golden.mjs — do not hand-edit.",
  fzfVersion,
  options: { casing: "case-insensitive", selector: true },
  minRelativeScore: MIN_RELATIVE_SCORE,
  haystacks,
  cases,
};

const outPath = join(repoRoot, "apps/gui/src-tauri/fixtures/fzf-golden.json");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${JSON.stringify(out, null, 1)}\n`);
console.log(
  `wrote ${outPath}: ${haystacks.length} haystacks, ${cases.length} queries (fzf ${fzfVersion})`,
);
