# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cannet_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cannet_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61nnet_info.proto\x12\x06\x63\x61nnet\"\x13\n\x11ServerInfoRequest\"N\n\x12ServerInfoResponse\x12\x10\n\x08packages\x18\x01 \x03(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x15\n\rinstance_name\x18\x03 \x01(\t2Q\n\nCannetInfo\x12\x43\n\nServerInfo\x12\x19.cannet.ServerInfoRequest\x1a\x1a.cannet.ServerInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cannet_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERINFOREQUEST']._serialized_start=29
  _globals['_SERVERINFOREQUEST']._serialized_end=48
  _globals['_SERVERINFORESPONSE']._serialized_start=50
  _globals['_SERVERINFORESPONSE']._serialized_end=128
  _globals['_CANNETINFO']._serialized_start=130
  _globals['_CANNETINFO']._serialized_end=211
# @@protoc_insertion_point(module_scope)
