//! Generate the MF4 import-time-origin fixture in
//! `examples/time-origins/`.
//!
//! Run from the repository root:
//!
//! ```text
//! cargo run -p cannet-mdf --example gen_mdf_time_origin_fixtures
//! ```
//!
//! `wall-clock-signals.mf4` states an `hd_start_time_ns`, so every
//! timestamp it carries is a wall clock (ADR 0024). What makes it a
//! time-origin fixture is *which* of those timestamps is earliest: the
//! file's first **frame** is half a second in, while a message-independent
//! signal group and an `##EV` event both start before it. A capture that
//! anchors on the first frame it ingests therefore anchors above its own
//! earliest sample.
//!
//! The BLF half of the pair is generated by
//! `cargo run -p cannet-blf --example gen_time_origin_fixtures`.

use std::path::{Path, PathBuf};

use cannet_core::{CanFrame, CanId, Direction};
use cannet_mdf::{FileSignal, MdfCaptureLayout, MdfCaptureWriter, MdfEvent};

/// 2024-03-01T12:00:00Z — `hd_start_time_ns`, and the same wall clock
/// the BLF half of this fixture pair states.
const WALL_CLOCK_NS: u64 = 1_709_294_400_000_000_000;

/// `EngineData` from `time-origins.dbc`.
const ENGINE_DATA_ID: u32 = 0x100;
/// `Status` from `time-origins.dbc`.
const STATUS_ID: u32 = 0x200;

/// How far into the file the first CAN frame sits. Everything below it —
/// the signal groups and the first event — is what a first-frame anchor
/// pushes negative.
const FIRST_FRAME_OFFSET_NS: u64 = 500_000_000;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let dir: PathBuf = std::env::args_os().nth(1).map_or_else(
        || Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples/time-origins"),
        PathBuf::from,
    );
    std::fs::create_dir_all(&dir)?;
    write_wall_clock_signals(&dir.join("wall-clock-signals.mf4"))?;
    Ok(())
}

fn frame(ts_ns: u64, id: u32, data: Vec<u8>) -> CanFrame {
    CanFrame::classic(
        ts_ns,
        0,
        CanId::standard(id).expect("fixture ids are 11-bit"),
        Direction::Rx,
        data,
    )
    .expect("fixture frames are well formed")
}

/// Payload for `EngineData` at `i` — matches the BLF fixture's shape so
/// the same DBC decodes both to the same-looking series.
fn engine_payload(i: u64) -> Vec<u8> {
    let rpm = u16::try_from(800 + (i * 37) % 4_800).unwrap_or(u16::MAX);
    let temp = i8::try_from(i64::try_from(i % 90).unwrap_or(0) - 40).unwrap_or(0);
    let mut data = vec![0u8; 8];
    data[0..2].copy_from_slice(&rpm.to_le_bytes());
    data[2] = temp.to_le_bytes()[0];
    data
}

/// Payload for `Status` at `i`.
fn status_payload(i: u64) -> Vec<u8> {
    let mut data = vec![0u8; 8];
    data[0] = u8::try_from((i / 10) % 3).unwrap_or(0);
    data[1] = u8::try_from(i % 256).unwrap_or(0);
    data
}

fn write_wall_clock_signals(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let mut writer = MdfCaptureWriter::create(
        path,
        MdfCaptureLayout {
            start_time_ns: WALL_CLOCK_NS,
            max_payload_len: 8,
        },
    )?;

    // Frames: 100 × 20 ms, starting half a second in.
    for i in 0..100u64 {
        let t = WALL_CLOCK_NS + FIRST_FRAME_OFFSET_NS + i * 20_000_000;
        writer.append_frame(&frame(t, ENGINE_DATA_ID, engine_payload(i)))?;
        if i % 5 == 0 {
            writer.append_frame(&frame(t + 1_000_000, STATUS_ID, status_payload(i)))?;
        }
    }

    // A message-independent signal group whose first sample is at the
    // file's own zero — 500 ms before the first frame.
    let n = 50u32;
    let timestamps_ns: Vec<u64> = (0..u64::from(n))
        .map(|i| WALL_CLOCK_NS + i * 50_000_000)
        .collect();
    writer.add_signal(
        Some("Ambient".into()),
        FileSignal {
            name: "AmbientTemp".into(),
            unit: Some("degC".into()),
            conversion: None,
            value_table: Vec::new(),
            timestamps_ns: timestamps_ns.clone(),
            values: (0..n).map(|i| 18.0 + f64::from(i) * 0.1).collect(),
        },
    );

    // Events straddling the first frame: one before it, one after.
    writer.add_event(MdfEvent {
        timestamp_ns: WALL_CLOCK_NS + 100_000_000,
        name: "before first frame".into(),
        properties: vec![("cannet.id".into(), "time-origins-0".into())],
        ..MdfEvent::default()
    });
    writer.add_event(MdfEvent {
        timestamp_ns: WALL_CLOCK_NS + 1_500_000_000,
        name: "mid capture".into(),
        properties: vec![("cannet.id".into(), "time-origins-1".into())],
        ..MdfEvent::default()
    });

    writer.finish()?;
    Ok(())
}
